### ISSUE TITLE
[Question] Why did you switch to all-at-once parsing?

### ISSUE THREAD

**Issue by aymanosman** [lpgauth/anchor#22]
https://github.com/lpgauth/anchor/pull/19/commits/4d0af5e445a44ac31e9e821b7d3ef2ae4002f4ba

Just curious. Does that not mean you won't  be able to handle a response that is split over many packets? Or is this handled by a layer above?

**Comment by lpgauth** [comment]
Hi @aymanosman,
This is for performance reason, it saves a few tuple updates and function calls. Request spawning multiple packets still work but will have to reparse the header which should still be faster unless the number of packets is huge.
