### ISSUE TITLE
Add support for text protocol

### ISSUE THREAD

**Issue by silviucpp** [lpgauth/anchor#7]
Hello,

Any idea when this project can support the text protocol ? twemproxy is very popular and unfortunately is supporting only text protocol.

Silviu

**Comment by lpgauth** [comment]
Hi @silviucpp,
I started working on ascii protocol support. I'll probably finish it this weekend...

https://github.com/lpgauth/anchor/tree/ascii

**Comment by silviucpp** [comment]
Hello,

Any idea when you will have an working version using ascii protocol ?

Silviu

**Comment by lpgauth** [comment]
@silviucpp turns out it's a bit more complicated then I expected since the protocol is not 100% compatible... I'm almost done a first version I just need to clean it up. Probably by end of week I'll have a fully functional branch.

**Comment by silviucpp** [comment]
Hello,

I don't want to stress you but your project seems for me one of the most clean driver for memcache in erlang :) For this reason I want to integrate it into my projects.. Do yo have any news on the ascii protocol which unfortunately for me is the one I need..

Silviu

**Comment by lpgauth** [comment]
Hi, I've decided not to support ASCII protocol. The interface is too different to support along side the binary protocol without major architectural changes.
